### ISSUE TITLE
'Go!' button functionallity is broken for URLs

### ISSUE THREAD

**Issue by norpol** [screeninvader/outta_space#13]
You can't submit an URL with the `Go!` button, you always need to push `Enter` when focus is inside the input form. Devs are informed, dropping this here until it is fixed - so other users have the possibility to stay informed.

**Comment by phaer** [comment]
Can't test it at the moment: That does solve the problem that clicks on "Go!" did not actually submit urls to the screeninvader?

**Comment by jaeh** [comment]
yep,
the blur and click events were triggered simultaneously and blur was executed faster/earlier than the click event, leading to the url always being empty once the click triggered.

by checking if the relatedTarget is the go button i circumvent this problem.

**Comment by phaer** [comment]
Ah yes, or by setting a timeout. To be honest, I am not too excited by broken core features in the master branch, especially when they are broken due to behavior we found before (blur handler and click events on search result links).

Either full test coverage or 4-6 eyes on each merge seems to be inevitably if we want to create a somewhat stable release while maintaining a rather chaotic "roadmap". Full test coverage seems quite unlikely, so I'd argue for the latter.

**Comment by norpol** [comment]
Problem still persists...
